{{- $defaults := .Values.vaultDynamicSecrets.defaults -}}
{{- range .Values.vaultDynamicSecrets.items }}
{{- $provider := .provider | default dict -}}
{{- $defaultProvider := $defaults.provider | default dict -}}
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/generators.external-secrets.io/vaultdynamicsecret_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: {{ required "vaultDynamicSecrets.items[].name is required" .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" $ | nindent 4 }}
spec:
  path: {{ required "vaultDynamicSecrets.items[].path is required" .path | quote }}
  method: {{ .method | default $defaults.method | default "GET" | quote }}
  provider:
    server: {{ (dig "server" "" $provider | default (dig "server" "" $defaultProvider)) | quote }}
    auth:
      kubernetes:
        mountPath: {{ (dig "auth" "kubernetes" "mountPath" "" $provider | default (dig "auth" "kubernetes" "mountPath" "" $defaultProvider)) | quote }}
        role: {{ (dig "auth" "kubernetes" "role" "" $provider | default (dig "auth" "kubernetes" "role" "" $defaultProvider) | default $.Release.Namespace) | quote }}
        secretRef:
          name: {{ (dig "auth" "kubernetes" "secretRef" "name" "" $provider | default (dig "auth" "kubernetes" "secretRef" "name" "" $defaultProvider)) | quote }}
          key: {{ (dig "auth" "kubernetes" "secretRef" "key" "" $provider | default (dig "auth" "kubernetes" "secretRef" "key" "" $defaultProvider)) | quote }}
    {{- $caProvider := (dig "caProvider" dict $provider | default (dig "caProvider" dict $defaultProvider)) }}
    {{- with $caProvider }}
    caProvider:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
