---
apiVersion: v2
name: cardiac-uhn
description: App-template based Helm chart for Cardiac UHN applications
type: application
version: 0.1.1
kubeVersion: ">=1.28.0-0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  app-template.uhn.io/source: external-example/helm-charts/charts/other/app-template
  app-template.uhn.io/dhp-source: external-example/generic-dhp-application-helm
  artifacthub.io/changes: |-
    - kind: fixed
      description: Reference existing vault-auth ServiceAccount instead of creating it.
